server:
  applicationConnectors:
    - type: http
      port: 8080
  adminConnectors:
    - type: http
      port: 8081

logging:
  level: INFO

database:
  driverClass: org.mariadb.jdbc.Driver
  url: jdbc:mariadb://host.docker.internal:3307/todo_tracker
  user: root
  password: SanRed@1998



