version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db
    ports:
      - "8080:8080"
    environment:

      DB_HOST: host.docker.internal
      DB_PORT: 3306
      DB_USER: root
      DB_PASSWORD: SanRed@1998
      DB_NAME: todo_tracker
      DB_URL: jdbc:mariadb://host.docker.internal:3307/todo_tracker

  db:
    image: mariadb:10.6
    container_name: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: SanRed@1998

    ports:
      - "3308:3306"






